/*
 * Copyright 2018 Marek Morawiec
 * User: marek
 * Date: 01.06.2018
 * Time: 17:44
 */

package pl.poligro.Utils;

import java.awt.*;
import java.time.format.DateTimeFormatter;

public interface GlobalConst {

    Dimension SCREEN_SIZE = Toolkit.getDefaultToolkit().getScreenSize();

    Integer FPS = 60;

    Integer TILE_SIZE_PX = 40;

    Integer DESKTOP_RESOLUTION_WIDTH = ((int) SCREEN_SIZE.getWidth());
    Integer DESKTOP_RESOLUTION_HEIGHT = ((int) SCREEN_SIZE.getHeight());

    Integer MAIN_WINDOW_WIDTH_TILES = DESKTOP_RESOLUTION_WIDTH / TILE_SIZE_PX;
    Integer MAIN_WINDOW_HEIGHT_TILES = DESKTOP_RESOLUTION_HEIGHT / TILE_SIZE_PX;

    Integer UI_WINDOW_WIDTH_TILES = 8;
    Integer UI_WINDOW_HEIGHT_TILES = MAIN_WINDOW_HEIGHT_TILES;

    Integer GAME_WINDOW_WIDTH_TILES = MAIN_WINDOW_WIDTH_TILES - UI_WINDOW_WIDTH_TILES;
    Integer GAME_WINDOW_HEIGHT_TILES = MAIN_WINDOW_HEIGHT_TILES;

    Integer GAME_WINDOW_START_POS_X = 0;
    Integer GAME_WINDOW_START_POS_Y = 0;

    Integer GAME_WINDOW_WIDTH_PX = GAME_WINDOW_WIDTH_TILES * TILE_SIZE_PX;
    Integer GAME_WINDOW_HEIGHT_PX = GAME_WINDOW_HEIGHT_TILES * TILE_SIZE_PX;

    Integer MAIN_WINDOW_WIDTH_PX = MAIN_WINDOW_WIDTH_TILES * TILE_SIZE_PX;
    Integer MAIN_WINDOW_HEIGHT_PX = MAIN_WINDOW_HEIGHT_TILES * TILE_SIZE_PX;

    Integer UI_WINDOW_START_POS_X = GAME_WINDOW_WIDTH_TILES * TILE_SIZE_PX;
    Integer UI_WINDOW_START_POS_Y = 0;

    Integer UI_WINDOW_WIDTH_PX = UI_WINDOW_WIDTH_TILES * TILE_SIZE_PX;
    Integer UI_WINDOW_HEIGHT_PX = UI_WINDOW_HEIGHT_TILES * TILE_SIZE_PX;

    DateTimeFormatter DEFAULT_DATE_TIME_FORMATER = DateTimeFormatter.ofPattern("HH:mm:ss");
}
