/*
 * Copyright 2018 Marek Morawiec
 * User: marek
 * Date: 01.06.2018
 * Time: 17:44
 */

package pl.poligro.Utils;

public interface GlobalConsts {

    Integer FPS = 60;

    Integer TILE_SIZE_PX = 48;

    Integer MAIN_WINDOW_WIDTH_TILES = 38;
    Integer MAIN_WINDOW_HEIGHT_TILES = 20;

    Integer UI_WINDOW_WIDTH_TILES = 8;
    Integer UI_WINDOW_HEIGHT_TILES = MAIN_WINDOW_HEIGHT_TILES;

    Integer GAME_WINDOW_WIDTH_TILES = MAIN_WINDOW_WIDTH_TILES - UI_WINDOW_WIDTH_TILES - 1;
    Integer GAME_WINDOW_HEIGHT_TILES = MAIN_WINDOW_HEIGHT_TILES - 1;

    Integer GAME_WINDOW_START_POS_X = 0;
    Integer GAME_WINDOW_START_POS_Y = 0;

    Integer GAME_WINDOW_WIDTH_PX = GAME_WINDOW_WIDTH_TILES * TILE_SIZE_PX;
    Integer GAME_WINDOW_HEIGHT_PX = GAME_WINDOW_HEIGHT_TILES * TILE_SIZE_PX;

    Integer MAIN_WINDOW_WIDTH_PX = MAIN_WINDOW_WIDTH_TILES * TILE_SIZE_PX;
    Integer MAIN_WINDOW_HEIGHT_PX = MAIN_WINDOW_HEIGHT_TILES * TILE_SIZE_PX;

    Integer UI_WINDOW_START_POS_X = GAME_WINDOW_WIDTH_TILES;
    Integer UI_WINDOW_START_POSY_Y = 0;

    Integer UI_WINDOW_WIDTH_PX = UI_WINDOW_WIDTH_TILES * TILE_SIZE_PX;
    Integer UI_WINDOW_HEIGHT_PX = UI_WINDOW_HEIGHT_TILES * TILE_SIZE_PX;
}
